apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: quiz
type: Opaque
data:
  mongo-uri: mongodb+srv://manasseh:b1t0cxeONdVytcen@cluster1.chjelr6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1


